name: ESLint and Jest tests

on:

push:

branches:

- main

jobs:

Deploy-Test:

runs-on: ubuntu-latest

name: Run ESLint and Jest

steps:

- uses: actions/checkout@v3

- uses: bahmutov/npm-install@v1

- run: npm run lint

- run: npm test
